# Generated by Django 3.2.2 on 2023-08-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_manager_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
